src/BeYourMarket.Web/Areas/Admin/Controllers/ListingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using BeYourMarket.Service;
using System.Threading.Tasks;
using BeYourMarket.Model.Models;
using Repository.Pattern.UnitOfWork;
using Newtonsoft.Json;
using BeYourMarket.Web.Extensions;
using BeYourMarket.Web.Models.Grids;
using BeYourMarket.Web.Models;
using BeYourMarket.Web.Utilities;
using ImageProcessor.Imaging.Formats;
using System.Drawing;
using ImageProcessor;
using System.IO;
using System.Text;
using BeYourMarket.Model.Enum;
using RestSharp;
using BeYourMarket.Web.Areas.Admin.Models;
using Postal;
using System.Net.Mail;
using System.Net;
using BeYourMarket.Service.Models;
using BeYourMarket.Core.Web;

namespace BeYourMarket.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ListingController : Controller
    {
        #region Fields
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        private readonly ISettingService _settingService;
        private readonly ISettingDictionaryService _settingDictionaryService;

        private readonly ICategoryService _categoryService;
        private readonly ICategoryListingTypeService _categoryListingTypeService;

        private readonly IListingService _listingService;
        private readonly IListingTypeService _listingTypeService;
        private readonly IListingReviewService _listingReviewService;

        private readonly ICustomFieldService _customFieldService;
        private readonly ICustomFieldCategoryService _customFieldCategoryService;
        private readonly ICustomFieldListingService _customFieldListingService;

        private readonly IContentPageService _contentPageService;

        private readonly IOrderService _orderService;

        private readonly IListingPictureService _listingPictureservice;
        private readonly IPictureService _pictureService;

        private readonly IEmailTemplateService _emailTemplateService;

        private readonly DataCacheService _dataCacheService;
        private readonly SqlDbService _sqlDbService;

        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        #endregion

        #region Properties
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        #endregion

        #region Constructor
        public ListingController(
            IUnitOfWorkAsync unitOfWorkAsync,
            ISettingService settingService,
            ICategoryService categoryService,
            ICategoryListingTypeService categoryListingTypeService,
            IListingService listingService,
            IListingTypeService listingTypeService,
            ICustomFieldService customFieldService,
            ICustomFieldCategoryService customFieldCategoryService,
            ICustomFieldListingService customFieldListingService,
            IContentPageService contentPageService,
            IOrderService orderService,
            ISettingDictionaryService settingDictionaryService,
            IEmailTemplateService emailTemplateService,
            IPictureService pictureService,
            IListingPictureService listingPictureservice,
            IListingReviewService listingReviewService,
            DataCacheService dataCacheService,
            SqlDbService sqlDbService)
        {
            _settingService = settingService;
            _settingDictionaryService = settingDictionaryService;

            _categoryService = categoryService;
            _categoryListingTypeService = categoryListingTypeService;

            _listingService = listingService;
            _listingTypeService = listingTypeService;

            _pictureService = pictureService;
            
            _listingPictureservice = listingPictureservice;
            _listingReviewService = listingReviewService;

            _customFieldService = customFieldService;
            _customFieldCategoryService = customFieldCategoryService;
            _customFieldListingService = customFieldListingService;

            _orderService = orderService;

            _emailTemplateService = emailTemplateService;
            _contentPageService = contentPageService;
            _unitOfWorkAsync = unitOfWorkAsync;
            _dataCacheService = dataCacheService;
            _sqlDbService = sqlDbService;
        }
        #endregion

        #region Methods
        public ActionResult Categories()
        {
            var categories = _categoryService.Queryable().OrderBy(x => x.Parent).ThenBy(x => x.Ordering).ToList().GenerateTree(x => x.ID, x => x.Parent);

            return View(categories);
        }


        public class CategoryJson
        {
            public int id { get; set; }

            public CategoryJson[] children { get; set; }
        }

        [HttpPost]
        public async Task<ActionResult> CategoriesUpdate(string JsonCategories)
        {
            var result = JsonConvert.DeserializeObject<CategoryJson[]>(JsonCategories);

            await SetCategoryOrdering(0, result);

            await _unitOfWorkAsync.SaveChangesAsync();

            _dataCacheService.RemoveCachedItem(CacheKeys.ListingTypes);
            _dataCacheService.RemoveCachedItem(CacheKeys.Categories);

            return RedirectToAction("Categories");
        }

        /// <summary>
        /// Recursive method to set category ordering
        /// </summary>
        /// <param name="json"></param>
        public async Task SetCategoryOrdering(int parent, CategoryJson[] json)
        {
            int sortOrder = 0;
            foreach (var item in json)
            {
                var category = await _categoryService.FindAsync(item.id);
                category.Parent = parent;
                category.Ordering = sortOrder;
                category.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Modified;

                _categoryService.Update(category);

                sortOrder++;

                if (item.children != null)
                {
                    await SetCategoryOrdering(item.id, item.children);
                }
            }
        }

        public async Task<ActionResult> CategoryUpdate(int? id)
        {
            Category category;

            var categoryModel = new CategoryModel();

            var ListingTypes = await _listingTypeService.Query().SelectAsync();
            categoryModel.ListingTypes = ListingTypes.ToList();

            if (id.HasValue)
            {
                category = await _categoryService.FindAsync(id);
                var categoryListingTypes = await _categoryListingTypeService.Query(x => x.CategoryID == id.Value).SelectAsync();
                categoryModel.CategoryListingTypeID = categoryListingTypes.Select(x => x.ListingTypeID).ToList();
            }
            else
                category = new Category() { Enabled = true };

            categoryModel.Category = category;

            return View(categoryModel);
        }

        [HttpPost]
        public async Task<ActionResult> CategoryUpdate(CategoryModel model)
        {
            if (model.Category.ID == 0)
            {
                model.Category.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Added;
                model.Category.Parent = 0;

                _categoryService.Insert(model.Category);
            }
            else
            {
                var categoryExisting = await _categoryService.FindAsync(model.Category.ID);

                categoryExisting.Name = model.Category.Name;
                categoryExisting.Description = model.Category.Description;
                categoryExisting.Enabled = model.Category.Enabled;

                categoryExisting.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Modified;

                _categoryService.Update(categoryExisting);
            }

            await _unitOfWorkAsync.SaveChangesAsync();

            // Delete existing category item types
            var ListingTypes = _categoryListingTypeService.Queryable().Where(x => x.CategoryID == model.Category.ID).Select(x => x.ID).ToList();
            foreach (var ListingTypeID in ListingTypes)
            {
                await _categoryListingTypeService.DeleteAsync(ListingTypeID);
            }

            // Insert category item types
            foreach (var categoryListingTypeID in model.CategoryListingTypeID)
            {
                _categoryListingTypeService.Insert(new CategoryListingType()
                {
                    CategoryID = model.Category.ID,
                    ListingTypeID = categoryListingTypeID,
                    ObjectState = Repository.Pattern.Infrastructure.ObjectState.Added
                });
            }

            await _unitOfWorkAsync.SaveChangesAsync();

            _dataCacheService.RemoveCachedItem(CacheKeys.ListingTypes);
            _dataCacheService.RemoveCachedItem(CacheKeys.Categories);

src/BeYourMarket.Web/Areas/Admin/Controllers/PluginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using BeYourMarket.Service;
using System.Threading.Tasks;
using BeYourMarket.Model.Models;
using Repository.Pattern.UnitOfWork;
using Newtonsoft.Json;
using BeYourMarket.Web.Extensions;
using BeYourMarket.Web.Models.Grids;
using BeYourMarket.Web.Models;
using BeYourMarket.Web.Utilities;
using ImageProcessor.Imaging.Formats;
using System.Drawing;
using ImageProcessor;
using System.IO;
using System.Text;
using BeYourMarket.Model.Enum;
using RestSharp;
using BeYourMarket.Web.Areas.Admin.Models;
using Postal;
using System.Net.Mail;
using System.Net;
using BeYourMarket.Service.Models;
using BeYourMarket.Core.Plugins;
using BeYourMarket.Core.Web;

namespace BeYourMarket.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class PluginController : Controller
    {
        #region Fields
        private readonly ISettingService _settingService;
        private readonly ISettingDictionaryService _settingDictionaryService;

        private readonly ICategoryService _categoryService;
        private readonly IListingService _listingService;

        private readonly DataCacheService _dataCacheService;

        private readonly IUnitOfWorkAsync _unitOfWorkAsync;

        private readonly IPluginFinder _pluginFinder;
        #endregion

        #region Constructor
        public PluginController(
            IUnitOfWorkAsync unitOfWorkAsync,
            ISettingService settingService,
            ISettingDictionaryService settingDictionaryService,
            ICategoryService categoryService,
            IListingService listingService,
            DataCacheService dataCacheService,
            IPluginFinder pluginFinder)
        {
            _settingService = settingService;
            _settingDictionaryService = settingDictionaryService;

            _categoryService = categoryService;
            _listingService = listingService;

            _unitOfWorkAsync = unitOfWorkAsync;
            _dataCacheService = dataCacheService;

            _pluginFinder = pluginFinder;
        }
        #endregion

        #region Methods
        public ActionResult Plugins()
        {
            var plugins = _pluginFinder.GetPluginDescriptors(LoadPluginsMode.All).OrderBy(x => x.DisplayOrder).AsQueryable();

            var grid = new PluginsGrid(plugins);

            return View(grid);
        }
        
        public ActionResult Configure(string systemName)
        {
            var pluginDescriptor = _pluginFinder.GetPluginDescriptorBySystemName(systemName);
            
            string actionUrl = string.Empty;

            if (typeof(IHookPlugin).IsAssignableFrom(pluginDescriptor.PluginType))
            {
                actionUrl = Url.Action("ConfigureHook", "Hook", new { systemName = pluginDescriptor.SystemName });
            }

            // check if there is actionUrl
            if (string.IsNullOrEmpty(actionUrl))
                return HttpNotFound();

            return Redirect(actionUrl);
        }

        public ActionResult Installer(string systemName, int pluginAction)
        {
            var pluginDescriptor = _pluginFinder.GetPluginDescriptorBySystemName(systemName, LoadPluginsMode.All);

            switch ((BeYourMarket.Model.Enum.Enum_PluginAction)pluginAction)
            {
                case Enum_PluginAction.Install:
                    pluginDescriptor.Instance().Install();
                    TempData[TempDataKeys.UserMessage] = string.Format("[[[{0} is installed]]]", systemName);
                    break;
                case Enum_PluginAction.Uninstall:                    
                    pluginDescriptor.Instance().Uninstall();
                    TempData[TempDataKeys.UserMessage] = string.Format("[[[{0} is uninstalled]]]", systemName);
                    break;
                case Enum_PluginAction.Enabled:
                    pluginDescriptor.Instance().Enable(true);
                    TempData[TempDataKeys.UserMessage] = string.Format("[[[{0} is enabled]]]", systemName);
                    break;
                case Enum_PluginAction.Disabled:
                    pluginDescriptor.Instance().Enable(false);
                    TempData[TempDataKeys.UserMessage] = string.Format("[[[{0} is disabled]]]", systemName);
                    break;
                default:
                    break;
            }                                    
            
            return RedirectToAction("Plugins");
        }


        #endregion
    }
}

src/BeYourMarket.Web/Areas/Admin/Views/Listing/Categories.cshtml
@model IEnumerable<BeYourMarket.Web.Extensions.TreeItem<BeYourMarket.Model.Models.Category>>

@section Styles {
    <link href="~/js/nestable/jquery.nestable.css" rel="stylesheet" />
}

@{
    ViewBag.Title = "[[[Categories]]]";
}

@helper DisplayTree(IEnumerable<BeYourMarket.Web.Extensions.TreeItem<BeYourMarket.Model.Models.Category>> categories)
{
    <ol class="dd-list">
        @foreach (var item in categories)
        {
            <li class="dd-item dd3-item" data-id="@item.Item.ID">
                <div class="dd-handle dd3-handle"></div>
                <div class="dd3-content">
                    @item.Item.Name
                    <div class="pull-right">
                        <a href="@Url.Action("CategoryUpdate", "Listing", new { id = @item.Item.ID })"><i class="fa fa-edit"></i> [[[Edit]]]</a>

                        <a href="javascript:void(0);" onclick="confirmDelete(@item.Item.ID, '@item.Item.Name');"><i class="fa fa-remove"></i> [[[Delete]]]</a>
                    </div>
                </div>
                @DisplayTree(item.Children)
            </li>
        }
    </ol>
}

<div class="wraper container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">[[[Categories]]]</h3>
                </div>

                <div class="panel-body">
                    @Html.Partial("_UserMessage")

                    <div class="alert alert-info">
                        <p>[[[Here you can add categories and subcategories. There shall always be one category for each listing.]]]</p>
                    </div>

                    <div class="row">
                        <div class="col-lg-10">
                            <a class="btn btn-primary" href="@Url.Action("CategoryUpdate", "Listing")"><i class="fa fa-plus"></i> [[[Add New]]]</a>
                        </div>
                    </div>

                    <hr />

                    <form action="@Url.Action("CategoriesUpdate", "Listing")" id="settingsForm" method="post" class="form-horizontal" role="form">
                        <input id="JsonCategories" name="JsonCategories" type="hidden" />

                        <div class="form-group">
                            <div class="col-lg-12">
                                <div class="dd nestable">
                                    @DisplayTree(Model)
                                </div>
                            </div>
                        </div>

                        <hr />

                        <div class="form-group">
                            <div class="col-lg-12">
                                <button id="submitBtn" class="btn btn-primary" type="submit"><i class="fa fa-save"></i> [[[Save]]]</button>
                                <a href="@Url.Action("Categories", "Listing")" class="btn btn-default"><i class="fa fa-remove"></i> [[[Cancel]]]</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/nestable/jquery.nestable.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.nestable')
                .nestable({
                    maxDepth: 2
                })
                .on('change', function (e) {
                    $('#JsonCategories').val(JSON.stringify($('.nestable').nestable('serialize')));
                });

            $('#JsonCategories').val(JSON.stringify($('.nestable').nestable('serialize')));
        });
    </script>

    <script type="text/javascript">
        function confirmDelete(id, title) {
            swal({
                title: "[[[Are you sure?]]]",
                text: "[[[You will delete all listings with the category ]]] " + title,
                type: "input",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "[[[Yes, delete it!]]]",
                cancelButtonText: "[[[No, cancel please!]]]",
                inputPlaceholder: "[[[Type DELETE to confirm delete]]]",
                closeOnConfirm: false,
                closeOnCancel: true
            }, function (inputValue) {

                if (inputValue === false)
                    return false;
                if (inputValue === "" || inputValue != "DELETE") {
                    swal.showInputError("[[[Type DELETE to confirm delete]]]"); return false
                }

                post('@Url.Action("CategoryDelete","Listing")', { id: id });

                swal("Deleted!", "[[[Category is deleted.]]]", "success");
            });
        }
    </script>
}

src/BeYourMarket.Web/Areas/Admin/Views/Listing/CategoryUpdate.cshtml
@model BeYourMarket.Web.Models.CategoryModel

@{
    ViewBag.Title = "[[[Category]]]";
}

<div class="wraper container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">[[[Category]]]</h3></div>
                <div class="panel-body">

                    <form action="@Url.Action("CategoryUpdate", "Listing")" id="settingsForm" method="post" class="form-horizontal" role="form">
                        @Html.HiddenFor(x => x.Category.ID)

                        <div class="form-group">
                            <label class="col-md-2 control-label">[[[Name]]]</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" id="Category_Name" name="Category.Name" value="@Model.Category.Name" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">[[[Description]]]</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" id="Category_Description" name="Category.Description" value="@Model.Category.Description" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <label class="cr-styled">
                                    <input checked="@Model.Category.Enabled" id="Category_Enabled" name="Category.Enabled" type="checkbox" value="true" />
                                    <i class="fa"></i>
                                    [[[Enabled]]]
                                </label>
                            </div>
                        </div>

                        <hr />
                        <div class="form-group">
                            <label class="col-md-2 control-label">[[[Listing Type]]]</label>
                            <div class="col-md-10">
                                <fieldset>
                                    @foreach (var option in Model.ListingTypes)
                                    {
                                        <input type="checkbox" id="CategoryListingTypeID" name="CategoryListingTypeID" value="@option.ID" checked="@Model.CategoryListingTypeID.Contains(option.ID)" required />
                                            <label for="CategoryListingTypeID">@option.Name</label>
                                    }
                                </fieldset>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> [[[Save]]]</button>
                                <a href="@Url.Action("Categories", "Listing")" class="btn btn-default"><i class="fa fa-remove"></i> [[[Cancel]]]</a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $.validator.addMethod('require-one', function (value) {
                if ($('#CategoryListingTypeID').is(':checked')) {
                    return $('.require-one:checked').size() > 0;
                } else {
                    return true;
                }
            }, 'Selecione pelo menos uma das opções.');
        });
    </script>
}

src/BeYourMarket.Web/Areas/Admin/Views/Listing/ListingTypeUpdate.cshtml
@model BeYourMarket.Model.Models.ListingType

@{
    ViewBag.Title = "[[[Listing Type Update]]]";
}

@section Styles {
    <link href="~/css/select2/select2.css" rel="stylesheet" />
}

<div class="wraper container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">[[[Listing Type]]]</h3></div>
                <div class="panel-body">
                    <form action="@Url.Action("ListingTypeUpdate", "Listing")" id="listingTypeForm" method="post" class="form-horizontal" role="form">

                        @Html.HiddenFor(x => x.ID)

                        @Html.ValidationSummary(true, string.Empty, new { @class = "alert alert-danger" })

                        <div class="form-group">
                            <label class="col-sm-2 control-label">ID</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">@Model.ID</p>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">[[[Name]]]</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" placeholder="[[[e.g. Offer]]]" required>
                            </div>
                        </div>

                        <fieldset>
                            <div class="form-group">
                                <label class="col-md-2 control-label">[[[Button Label]]]</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="ButtonLabel" name="ButtonLabel" value="@Model.ButtonLabel" placeholder="[[[e.g. Book]]]" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <label class="cr-styled">
                                        <input checked="@Model.PriceEnabled" id="PriceEnabled" name="PriceEnabled" type="checkbox" value="true" />
                                        <i class="fa"></i>
                                        [[[Price Enabled]]]
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label">[[[Price Unit Label]]]</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="PriceUnitLabel" name="PriceUnitLabel" value="@Model.PriceUnitLabel" placeholder="[[[e.g. Per day]]]">
                                </div>
                            </div>
                        </fieldset>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <label class="cr-styled">
                                    <input checked="@Model.ShippingEnabled" id="ShippingEnabled" name="ShippingEnabled" type="checkbox" value="true" />
                                    <i class="fa"></i>
                                    [[[Shipping Enabled]]]
                                </label>
                            </div>
                        </div>

                        <hr />

                        <div class="col-md-offset-2 col-md-10 alert alert-info">
                            <h4>[[[Payment]]]</h4>
                            <p>[[[To configure payment method for payout, please configure the Payment plugin]]]</p>
                            <p>
                                <a class="btn btn-default" href="@Url.Action("Plugins", "Plugin", new { area = "Admin", id = "" })">[[[Configure Plugins]]]</a>
                            </p>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <label class="cr-styled">
                                    <input checked="@Model.PaymentEnabled" id="PaymentEnabled" name="PaymentEnabled" type="checkbox" value="true" />
                                    <i class="fa"></i>
                                    [[[Payment Enabled]]]
                                </label>
                            </div>
                        </div>

                        <fieldset id="orderTypeFieldSet" @(Model.PaymentEnabled ? "" : "disabled")>
                            <div class="form-group">
                                <label class="col-md-2 control-label">[[[Order Type]]]</label>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(m => m.OrderTypeID, EnumHelper.GetSelectList(typeof(BeYourMarket.Model.Enum.Enum_ListingOrderType)), new { @class = "form-control", required = "" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label">[[[Order Type Label]]]</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="OrderTypeLabel" name="OrderTypeLabel" value="@Model.OrderTypeLabel" placeholder="[[[e.g. Number of days]]]">
                                </div>
                            </div>
                        </fieldset>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> [[[Save]]]</button>
                                <a href="@Url.Action("ListingTypes", "Listing")" class="btn btn-default"><i class="fa fa-remove"></i> [[[Cancel]]]</a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/css/select2/select2.min.js"></script>

    <script>
        $(document).ready(function () {
            // Select2
            $(".select2").select2({
                width: '100%'
            });

            // Payment
            $('#PaymentEnabled').on('change', function () {
                if (this.checked) {
                    $("#orderTypeFieldSet").removeAttr("disabled");
                }
                else {
                    $("#orderTypeFieldSet").attr("disabled", "disabled");
                }
            });
        });

    </script>
}